[main]
# --- Appearance ---

font=FiraCode Nerd Font:size=14

use-bold=yes

dpi-aware=no

# --- Window Layout ---

width=45
lines=8

horizontal-pad=20
vertical-pad=20
inner-pad=10
.
prompt=" "

show-actions=no

layer=overlay

# --- Behavior ---

terminal=kitty

icon-theme=Papirus-Dark

match-mode=fzf

# --- Theming (Colors) ---
include=~/.config/fuzzel/catppuccin-fuzzel/themes/catppuccin-mocha/mauve.ini

[border]
radius=12
width=2